# Task 18
# version: "3"
# services:
#   db:
#     image: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: testdb
#   app:
#     image: python:3.11
#     command: python -c "print('App running')"

#Task 19
# version: "3"
# services:
#   backend:
#     build: .
#     ports:
#       - "5000:5000"
#   db:
#     image: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root

#Task 20
# version: "3"
# services:
#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#   db:
#     image: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: fastapi_db