version: "3.8"

services:

  mongo:
    image: mongo:6.0
    container_name: flaskcart_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flaskapp:
    build: .
    container_name: flaskcart_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/flaskcart
    depends_on:
      - mongo

volumes:
  mongo_data: