version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_company
    environment:
      MYSQL_ROOT_PASSWORD: NewPassword123!
      MYSQL_DATABASE: company
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
